# -*- mode: python ; coding: utf-8 -*-
import os

ROOT = os.path.abspath(".")
CLIENT = os.path.join(ROOT, "client")
BACKEND = os.path.join(CLIENT, "backend")
FRONTEND_DIST = os.path.join(CLIENT, "frontend", "dist")

a = Analysis(
    [os.path.join(CLIENT, "launcher.pyw")],
    pathex=[CLIENT, BACKEND],
    binaries=[],
    datas=[
        # Backend Python dosyaları (açık liste)
        (os.path.join(BACKEND, "main.py"),       "backend"),
        (os.path.join(BACKEND, "database.py"),   "backend"),
        (os.path.join(BACKEND, "models.py"),     "backend"),
        (os.path.join(BACKEND, "auth.py"),       "backend"),
        (os.path.join(BACKEND, "bot_engine.py"), "backend"),
        (os.path.join(BACKEND, "gsc_engine.py"), "backend"),
        (os.path.join(BACKEND, "config.json"),   "backend"),
        (os.path.join(BACKEND, "routers", "auth_router.py"), "backend/routers"),
        (os.path.join(BACKEND, "routers", "__init__.py"),   "backend/routers"),
        # Frontend statik dosyalar
        (FRONTEND_DIST, "frontend/dist"),
        # Logo
        (os.path.join(ROOT, "logo.ico"), "."),
    ],
    hiddenimports=[
        # Backend uygulama modülleri (PYZ'a derlensin)
        "main",
        "database",
        "models",
        "bot_engine",
        "gsc_engine",
        "playwright",
        "playwright.async_api",
        "greenlet",
        "auth",
        "routers",
        "routers.auth_router",
        "license_client",
        "uvicorn",
        "uvicorn.main",
        "uvicorn.config",
        "uvicorn.server",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "uvicorn.lifespan.off",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.http.httptools_impl",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.protocols.websockets.websockets_impl",
        "uvicorn.protocols.websockets.wsproto_impl",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.loops.asyncio",
        "fastapi",
        "fastapi.staticfiles",
        "fastapi.responses",
        "starlette",
        "starlette.staticfiles",
        "starlette.responses",
        "aiofiles",
        "aiosqlite",
        "sqlalchemy",
        "sqlalchemy.dialects.sqlite",
        "sqlalchemy.ext.asyncio",
        "pydantic",
        "pydantic_core",
        "passlib",
        "passlib.handlers",
        "passlib.handlers.bcrypt",
        "bcrypt",
        "jose",
        "jose.jwt",
        "multipart",
        "aiohttp",
        "curl_cffi",
        "bs4",
        "customtkinter",
        "PIL",
        "pystray",
        "win32api",
        "win32con",
        "win32gui",
        "winreg",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["test_*", "pytest"],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="RequestBot",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(ROOT, "logo.ico"),
    onefile=True,
)
